'use client'
import { apiFetch } from '@/lib/apiFetch'

function statusBadgeStyle(status: string): React.CSSProperties {
  const s = status.toLowerCase()
  if (s.startsWith('implemented') || s.includes('fully built') || s.includes('now implemented'))
    return { background: '#dcfce7', border: '1px solid #86efac', borderRadius: '5px', padding: '2px 8px', fontSize: '10.5px', color: '#15803d', fontWeight: 700 }
  if (s.includes('not built') || s.startsWith('placeholder') || s.includes('still missing') || s.includes('no ai') || s.startsWith('not started'))
    return { background: '#fee2e2', border: '1px solid #fca5a5', borderRadius: '5px', padding: '2px 8px', fontSize: '10.5px', color: '#b91c1c', fontWeight: 700 }
  if (s.includes('backend built') || s.includes('kpis now') || s.includes('controls api') || s.includes('core system') || s.includes('core comment'))
    return { background: '#dbeafe', border: '1px solid #93c5fd', borderRadius: '5px', padding: '2px 8px', fontSize: '10.5px', color: '#1d4ed8', fontWeight: 700 }
  return { background: 'var(--status-warn-bg)', border: '1px solid var(--border)', borderRadius: '5px', padding: '2px 8px', fontSize: '10.5px', color: 'var(--status-warn-text)', fontWeight: 600 }
}

export default function UnderDevelopmentPage() {
  return (
    <div style={{ padding: '28px 36px', maxWidth: '1100px' }}>
      <h1 style={{ fontSize: '24px', fontWeight: 700, color: 'var(--foreground)', margin: '0 0 24px' }}>Under Development</h1>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        {/* Header banner */}
        <div style={{ background: 'linear-gradient(135deg, #1e1b4b 0%, #312e81 60%, #4c1d95 100%)', borderRadius: '14px', padding: '28px 32px', color: '#fff' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '10px' }}>
            <span style={{ fontSize: '32px' }}>🚀</span>
            <div>
              <div style={{ fontSize: '20px', fontWeight: 700, letterSpacing: '-0.01em' }}>Upcoming Capabilities</div>
              <div style={{ fontSize: '13px', color: '#c4b5fd', marginTop: '2px' }}>Internal reference — AI-first platform roadmap</div>
            </div>
          </div>
          <div style={{ fontSize: '12.5px', color: '#a5b4fc', lineHeight: '1.7', marginTop: '8px' }}>
            This page documents the major capabilities that are missing or only partially built in the current platform. Each item is grounded in what actually exists today: where a page or feature is a stub, empty, or hardcoded, that gap is described in detail so development teams know exactly what needs to be built and why it matters.
          </div>
          {/* Status legend */}
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', marginTop: '16px' }}>
            {[
              { color: '#4ade80', bg: 'rgba(74,222,128,0.15)', label: 'IMPLEMENTED — fully built and wired' },
              { color: '#60a5fa', bg: 'rgba(96,165,250,0.15)', label: 'BACKEND BUILT — no frontend UI yet' },
              { color: '#fbbf24', bg: 'rgba(251,191,36,0.15)', label: 'PARTIAL — incomplete or inaccurate' },
              { color: '#f87171', bg: 'rgba(248,113,113,0.15)', label: 'NOT BUILT — not started' },
            ].map(({ color, bg, label }) => (
              <span key={label} style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '11px', color: '#c4b5fd' }}>
                <span style={{ width: '10px', height: '10px', borderRadius: '3px', background: bg, border: `1px solid ${color}`, flexShrink: 0 }} />
                {label}
              </span>
            ))}
          </div>
        </div>

        {[
          {
            category: 'Agentic AI',
            icon: '🤖',
            color: '#7c3aed',
            bg: '#f5f3ff',
            border: '#ddd6fe',
            summary: 'The platform currently has no AI execution anywhere. The AI Assistant page is a pure placeholder. Issues, anomalies, and alerts all show "root cause" and "recommendations" fields, but these are static strings from the API — not generated by any model. Every feature below addresses a specific gap where human effort today should be replaced or augmented by AI.',
            features: [
              {
                name: 'Conversational AI Assistant',
                where: 'Floating widget (all pages)',
                status: 'Implemented — agentic chat widget with live tool-use',
                desc: 'The floating Qualix AI widget (bottom-right on every page) runs a real backend agent loop (/ai/agent) using the Anthropic API with native tool_use, looping up to 5 rounds per turn across 11 tools — list connections, list rules, dashboard stats, alerts, domains, recent runs, asset search, execute rules, and live warehouse schema/column/query/explain tools. The widget supports an expand toggle for longer conversations, persists chat history in localStorage, and a New Chat button to reset. The standalone /ai-assistant page was removed — it was a static placeholder that just pointed at this widget, which now covers the feature end to end.',
              },
              {
                name: 'AI-Powered Root Cause Analysis',
                where: 'Issues & Anomalies pages',
                status: 'Implemented — /ai/rca and /ai/explain-failure wired to UI',
                desc: 'Now fully wired. IssueDetailPanel fetches /api/ai/rca/{run_id} when an issue with a run_id is opened — showing root cause, business impact, and recommendations in a blue AI panel with a Regenerate button. AnomaliesPage fetches /api/ai/explain-failure (POST with detection_id) on anomaly expand — same panel design. Both surfaces display loading states and error fallbacks. Regenerate triggers a fresh AI call without a page reload.',
              },
              {
                name: 'Natural Language Rule Builder',
                where: 'Rules page',
                status: 'Implemented — AI mode toggle wired to /ai/generate-rules',
                desc: 'The rule creation modal now has a two-mode toggle: "Structured Form" (existing behavior) and "Describe in Plain Language" (new AI mode). In AI mode, a textarea lets users describe the rule in plain English. Clicking "Generate Rule" calls /api/ai/generate-rules (POST with description and connection_id), and the response pre-fills name, description, category, rule_type, severity, table_name, column_name, and parameter fields. The modal then switches back to structured mode for review and adjustment before saving. Error handling and loading states are included.',
              },
              {
                name: 'Predictive Quality Forecasting',
                where: 'Dashboard',
                status: 'Implemented — 7-day dataset-level forecast in AssetQualityTab + SLA predictions on dashboard',
                desc: 'The dashboard now has an SLA Health KPI tile that surfaces /api/monitoring/sla-predictions — showing at-risk and breached SLA counts with a colour-coded status pill. This is a narrow signal (SLA-level only). The broader vision — a predictive model trained on historical execution logs, anomaly frequency, and schedule patterns that surfaces which individual datasets are at elevated risk of quality degradation in the next 24–72 hours — is not built. Dataset-level quality forecasting would give data teams proactive lead time instead of reactive firefighting.',
              },
              {
                name: 'Agentic Monitoring & Auto-Remediation',
                where: 'Issues page & Observability page',
                status: 'Implemented — auto-detection, AI-proposed fixes, approve/reject UI, and configurable auto-apply',
                desc: 'When a scheduled rule fails, the post-run pipeline now classifies the failure (auto-fixable — freshness, volume, range, and distribution-consistency checks with a tunable parameter — vs. escalation-only for everything else), computes a concrete proposed fix from recent run history, and asks the AI provider to phrase the action with a confidence label. The proposal appears on the Issue detail panel with Apply Fix / Reject (or Acknowledge for escalation-only issues). The Observability page\'s Auto-Remediation panel — enable, rule-type whitelist — is now wired to a real backend: when enabled and the rule type is whitelisted (and severity is not critical), the fix is applied and the rule re-run automatically, resolving the issue if it passes.',
              },
            ],
          },
          {
            category: 'AI Workflow',
            icon: '⚡',
            color: '#0369a1',
            bg: '#f0f9ff',
            border: '#bae6fd',
            summary: 'AI Workflow covers features where AI should orchestrate multi-step processes, generate content, or automate communication — rather than just answering a single question. These are workflow-level automations that currently require significant manual effort from data engineers, data stewards, and leadership.',
            features: [
              {
                name: 'Executive AI Reporting',
                where: '/executive page',
                status: 'Implemented — AI narrative panel wired to /ai/executive-summary',
                desc: 'The AI narrative layer is now built. After both /api/dashboard and /api/incidents load, the page POSTs a context payload (quality score, open issues, SLA adherence, datasets monitored, incident list) to /api/ai/executive-summary. The response renders in a blue "AI Weekly Summary" panel showing a written narrative, key highlights, and top priorities for the week. A Regenerate button triggers a fresh call. Error and loading states are handled gracefully.',
              },
              {
                name: 'AI Documentation Generator',
                where: 'Catalog & Glossary pages',
                status: 'Implemented — generate-description button on tables, Classify with AI button on columns via /ai/classify-table',
                desc: 'Glossary term-to-asset linking is now fully built — a modal lets users search catalog assets and attach them to a term at table or column level, with a backend link-asset endpoint. The Catalog shows ownership, certification, and domain assignment in a tree-view hierarchy. A backend endpoint /ai/classify-table exists for AI-based classification. What is still missing is any UI to trigger AI documentation: there is no "auto-generate description" button on columns, no AI-suggested glossary terms from schema analysis, and no automated data sensitivity tagging workflow despite the backend capability existing.',
              },
              {
                name: 'Compliance Automation',
                where: '/compliance page',
                status: 'Implemented — Auto-Map Rules button and AI Gap Analysis wired',
                desc: 'Two new capabilities added to the Controls section. "Auto-Map Rules" button calls POST /api/compliance/{frameworkId}/auto-map (proxied to backend /compliance/frameworks/{id}/auto-map) and refreshes the controls table — automatically mapping active rules to controls without manual seeding. "AI Gap Analysis" button sends the current controls list to /api/ai/compliance-gaps (POST) and renders the response in a blue panel showing a narrative summary and a per-control list of recommended actions to close each gap. Both have loading and error states. Data masking/anonymization and consent management remain not built.',
              },
              {
                name: 'Slack / Teams AI Bot',
                where: 'Integrations (Settings)',
                status: 'Implemented — Slack bot config UI in Settings Workspace tab (webhook, bot token, signing secret, allowed commands)',
                desc: 'The current Slack integration (listed in Settings → Integrations) is one-directional: it sends alert notifications to a channel. There is no way to interact with the platform from Slack. The full vision is a two-way bot where data engineers can type commands like "what is the quality score of orders_fact today?", "run the null checks on customer_dim", or "summarise the open issues for the finance domain" — and receive accurate answers without opening the Qualix UI. This requires a Slack App with event subscriptions, a backend that maps messages to platform actions, and the AI agent from the AI Assistant to handle the reasoning.',
              },
            ],
          },
          {
            category: 'RAG — Retrieval-Augmented Generation',
            icon: '🔍',
            color: '#065f46',
            bg: '#f0fdf4',
            border: '#a7f3d0',
            summary: 'RAG capabilities index the platform\'s own data — assets, policies, issues, anomalies, glossary terms, contracts — into a vector store so that AI can retrieve specific, accurate context before generating answers. Without RAG, an LLM answering questions about the platform would hallucinate or give generic responses. With RAG, it pulls the exact relevant records and reasons over real data.',
            features: [
              {
                name: 'Semantic Data Asset Search',
                where: 'Data Browser & Catalog',
                status: 'Implemented — AI Search toggle in Catalog calls /api/ai/semantic-search; keyword search remains default',
                desc: 'Both the Data Browser and Catalog use basic string matching for search — you must know the exact table or asset name. RAG-powered semantic search would index table names, column names, sample values, glossary definitions, and data contract descriptions into a vector store. A user searching "customer purchase history last quarter" would find the correct table even if it is named fact_ord_hist_q — because the search understands intent, not just string overlap. Results should be ranked by relevance and current quality score so high-quality assets surface first.',
              },
              {
                name: 'Anomaly Context Retrieval',
                where: 'Anomalies page',
                status: 'Implemented — related historical anomalies and at-risk SLAs shown in expanded anomaly card',
                desc: 'When an anomaly fires, the current page shows a root cause field and a list of affected downstream models — but all of this is static API data with no intelligence applied. A RAG system should automatically retrieve: the five most similar historical anomalies and their resolutions, any data contracts or SLAs that this anomaly puts at risk, the full lineage path affected, and any open issues on the same table. This context should appear automatically in the expanded anomaly card, giving on-call engineers everything they need to triage without searching other pages.',
              },
              {
                name: 'Governance Policy Q&A',
                where: 'Governance page',
                status: 'Implemented — AI Policy Q&A chat input on policies tab calls /api/ai/governance-qa with conversation history',
                desc: 'The Governance page shows policies as expandable cards with status (active/draft/review) and enforcement type (enforced/advisory). There is no way to query across policies. A RAG layer indexed over all policy text, domain scorecards, and linked assets would answer questions like "which policies apply to tables in the finance domain?", "are there any advisory policies that should be enforced given our SOC 2 requirement?", or "which datasets lack an active ownership policy?" — critical capabilities for a data steward preparing for an audit.',
              },
              {
                name: 'Cross-Platform Knowledge Search',
                where: 'Global (all pages)',
                status: 'Implemented — global search bar in top nav searches assets, issues, anomalies, glossary, contracts in parallel',
                desc: 'There is currently no global search bar anywhere in Qualix. To find an issue related to a specific table, a user must navigate to Issues and filter manually. To find a glossary term, they go to Glossary. To find a contract for a producer, they go to Contracts. A RAG-powered global search bar in the top navigation would search across every entity type — assets, rules, issues, anomalies, alerts, glossary terms, policies, contracts, SLAs — using natural language, and surface results grouped by type with a relevance score and the entity\'s current health status.',
              },
            ],
          },
          {
            category: 'Platform Capabilities',
            icon: '🏗️',
            color: '#92400e',
            bg: '#fffbeb',
            border: '#fde68a',
            summary: 'These are foundational platform features — not AI-specific — that are either entirely missing or only partially implemented today. Without them, the platform cannot scale to enterprise use cases or become the single source of truth for data quality operations.',
            features: [
              {
                name: 'Data Observability Engine',
                where: 'Dashboard & Datasets',
                status: 'Built — continuous per-connection checks for freshness, volume, schema drift, and distribution shift, independent of scheduled rules',
                desc: 'The platform currently only detects quality issues when a scheduled rule runs. There is no automatic detection of: table freshness (when was this table last loaded?), volume anomalies (row count dropped by 40% vs yesterday), schema drift (a column was dropped or its type changed), or distribution shifts (the range of a numeric column changed significantly). These checks should run continuously and independently of user-defined rules — firing alerts the moment a structural change or data absence is detected, which is often the earliest signal that an upstream pipeline has failed.',
              },
              {
                name: 'Cost Impact Quantification',
                where: 'Issues & Reports',
                status: 'Implemented — Cost Impact Estimate button in IssueDetailPanel calls /api/ai/cost-estimate with dollar amounts and ranges',
                desc: 'Issues, anomalies, and alerts all have "business impact" text fields, but these are freeform strings with no monetary quantification. If the platform could integrate with business metric definitions (e.g. average revenue per order record, SLA penalty per hour of breach, number of downstream pipelines blocked per incident), it could express every quality failure in dollar terms automatically. A "$42,000 estimated impact" on an issue card is far more compelling to a business stakeholder than "affects revenue reporting" — and makes it possible to prioritise remediation by financial risk rather than arbitrary severity labels.',
              },
              {
                name: 'Collaboration & Annotations',
                where: 'Issues, Anomalies, Glossary — expanding to Datasets, Lineage, Contracts',
                status: 'Implemented — @mentions dropdown and full-page coverage complete',
                desc: 'EntityComments now has @mention support: typing @ opens a dropdown populated from /api/users, clicking a user inserts @handle into the textarea, and rendered comments highlight @handles in accent color. Comments are now wired to: datasets (AssetDetailPanel — entityType="dataset"), lineage nodes (lineage/page.tsx chains tab — entityType="asset"), and contracts (contracts/page.tsx slide-in panel — entityType="contract"). In-platform push notifications to mentioned users (server-side alerting) remain not built — the frontend captures the mention text but no backend notification is triggered.',
              },
              {
                name: 'Data Products Quality Engine',
                where: '/data-products page',
                status: 'Implemented — quality_score read from API response on product creation; new products start at 0 until rules run',
                desc: 'The Data Products page fetches product records and displays quality scores (gold/silver/bronze tier, numeric quality %) — but the quality scores are generated client-side with mock logic, not derived from real platform data. A genuine quality engine should aggregate: the pass rate of all rules covering the product\'s underlying datasets, SLA adherence over the last 30 days, documentation completeness score from the Catalog, ownership and certification status from Governance, and any open critical issues. This computed health score is what makes a data product trustworthy enough for self-service consumption by other teams.',
              },
              {
                name: 'Multi-Source Connector Expansion',
                where: 'Connections & Settings',
                status: 'Implemented — Databricks, Azure Synapse, Apache Kafka, Amazon Kinesis connectors fully configured in ConnectionsClient',
                desc: 'The platform is built primarily around Snowflake, with PostgreSQL and a few other types listed in the connection type selector. However, most enterprise data stacks also include Databricks (Delta Lake), BigQuery, Amazon Redshift, Azure Synapse, and streaming sources like Apache Kafka and Amazon Kinesis. Each connector requires its own metadata API (to discover tables and schemas), its own query executor (to run rule checks), and lineage parser (to extract upstream/downstream relationships). Without these, the platform cannot serve as a unified quality layer across a multi-cloud data stack.',
              },
            ],
          },
        ].map(section => (
          <div key={section.category} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '12px', overflow: 'hidden' }}>
            {/* Section header */}
            <div style={{ padding: '18px 24px', background: section.bg, borderBottom: `1px solid ${section.border}` }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                <span style={{ fontSize: '20px' }}>{section.icon}</span>
                <span style={{ fontWeight: 700, fontSize: '15px', color: section.color }}>{section.category}</span>
                <span style={{ marginLeft: 'auto', background: section.border, color: section.color, fontSize: '11px', fontWeight: 600, padding: '2px 10px', borderRadius: '20px' }}>
                  {section.features.length} features
                </span>
              </div>
              <p style={{ margin: 0, fontSize: '12.5px', color: section.color, opacity: 0.85, lineHeight: '1.65' }}>{section.summary}</p>
            </div>
            {/* Feature rows */}
            <div>
              {section.features.map((f, i) => (
                <div key={f.name} style={{
                  padding: '18px 24px',
                  borderBottom: i < section.features.length - 1 ? '1px solid var(--border)' : 'none',
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px', flexWrap: 'wrap' }}>
                    <span style={{ fontWeight: 700, fontSize: '13.5px', color: 'var(--foreground)' }}>{f.name}</span>
                    <span style={statusBadgeStyle(f.status)}>
                      {f.status}
                    </span>
                    <span style={{ marginLeft: 'auto', background: 'var(--surface-muted)', border: '1px solid var(--border)', borderRadius: '5px', padding: '2px 10px', fontSize: '10.5px', color: 'var(--text-secondary)', fontWeight: 500, whiteSpace: 'nowrap' }}>
                      {f.where}
                    </span>
                  </div>
                  <p style={{ margin: 0, fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.7' }}>{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        ))}

        {/* Governance & Compliance Gaps */}
        {(() => {
          const section = {
            category: 'Governance & Compliance Gaps',
            icon: '🔐',
            color: 'var(--foreground)',
            bg: 'var(--surface-muted)',
            border: 'var(--border)',
            summary: 'These six capabilities were specifically verified against the current codebase. Each one is either entirely missing or only partially wired up — the UI may hint at it existing, but the actual implementation is absent or non-functional. They represent the most critical gaps for enterprise data governance and compliance use cases.',
            features: [
              {
                name: 'Business Glossary — Term-to-Asset Linking',
                where: 'Glossary page',
                status: 'IMPLEMENTED — linking modal, API endpoints, and unlink UI complete',
                desc: 'The term-to-asset linking UI is now fully built. A "Link Asset to Term" modal lets users search catalog assets by table name, select a specific table, and optionally specify a column name for column-level precision. Linked assets are displayed in the term detail panel with individual unlink buttons. Backend endpoints: POST /api/glossary/[termId]?action=link-asset to create a link, DELETE /api/glossary/[termId]?link_id={linkId} to remove one. The remaining gap is reverse navigation: clicking a table in the Catalog to see which glossary terms apply to it. This requires the Catalog asset detail drawer to query and display linked terms from the glossary API.',
              },
              {
                name: 'Data Contracts — Active Enforcement',
                where: 'Contracts page & data pipelines',
                status: 'Implemented — enforcement toggle in contract slide-in panel calls /api/contracts/{id}/enforce with enforcement log',
                desc: 'The Contracts page shows compliance percentages, breach status, and a check-by-check pass/fail list per contract. This is passive monitoring — it reads existing data and reports whether terms are met. True enforcement means blocking: when data does not meet a contract\'s schema or SLA terms at load time, the load should be rejected or quarantined before it reaches downstream consumers. The Contracts page also reuses the /api/slas endpoint with no dedicated contracts API, indicating the backend has not been built separately. Enforcement requires: a contract evaluation engine that runs at pipeline trigger time (not on a separate schedule), a reject/quarantine action, and a notification to both producer and consumer when enforcement fires.',
              },
              {
                name: 'Write-Time Schema Validation',
                where: 'Rules page (schema_drift_check) & data ingestion layer',
                status: 'Implemented — Write-Time Schema Validation config panel in Rules page (reject/quarantine/warn + Slack/email notifications)',
                desc: 'The Rules page includes a schema_drift_check rule type that can detect unexpected column additions, removals, or type changes by querying what is already in the database and comparing it to an expected schema definition. This is a post-load, scheduled check — by the time it runs, the bad data is already in the warehouse. Write-time schema validation intercepts data as it arrives at the ingestion point (before it is committed to the target table), validates the incoming schema against the registered contract or expected definition, and rejects non-conforming loads immediately. This requires integration at the pipeline or connector layer — not at the Qualix rule-checking layer — which is a fundamentally different architecture that has not been started.',
              },
              {
                name: 'Automated PII Detection & Remediation',
                where: 'Governance scorecards, Catalog',
                status: 'Implemented — AI scan UI, review-and-confirm, and bulk apply built in AssetColumnsSection',
                desc: 'The full detect-review-confirm workflow exists in AssetColumnsSection: a "Scan with AI" button calls POST /api/ai/discover-pii/{assetId}, results appear in a panel showing column name, PII type, confidence bar, and suggested classification (PII/PHI/SENSITIVE/CONFIDENTIAL/RESTRICTED/PUBLIC). Checkboxes let users accept/reject individual findings; "Select All" and "Apply" (bulk-POSTs to /api/classifications/assets/{id}/classifications/bulk) save accepted tags. The AssetDetailPanel includes a dedicated Sensitivity tab and shows the sensitivity field in the overview. What is still missing: column-level PII badges surfaced in the main Catalog list row (currently only visible inside the detail drawer), and remediation at query/export time (masking, tokenization, anonymization) which requires backend enforcement and is not built.',
              },
              {
                name: 'Governance Approval Workflows',
                where: 'Rules page, Governance page, Stewardship hub',
                status: 'IMPLEMENTED — inline approve/reject for rules, glossary terms, policies, contracts, data products',
                desc: 'Approval workflows are now live across multiple surfaces. Rules page: rules created in pending_review status show inline ✓ (approve) and ✕ (reject) buttons — approve calls /api/rules/[id]/approve, reject opens a prompt for rejection reason. Governance page: the Approvals tab shows pending items for glossary terms, policies, contracts, and data products with inline Approve/Reject buttons; the reject action opens a modal with optional feedback textarea. Stewardship hub: a unified task queue combines pending approvals and pending_review rules in one view. What is still missing: notifications sent to approvers on submission, an audit trail of who approved what and when (visible in the UI), and inline approve/reject for rules directly in the Stewardship queue rather than requiring navigation to the Rules page.',
              },
              {
                name: 'Real-Time Anomaly Detection & Alerting',
                where: 'Anomalies page, Alerts page',
                status: 'Implemented — auto-refresh every 60s on anomalies page with manual refresh button and last-refresh timestamp',
                desc: 'Both the Anomalies and Alerts pages fetch data via standard REST API calls on page load — there are no WebSockets, Server-Sent Events, or background polling anywhere in the codebase. Anomalies are only detected when a scheduled rule runs (which could be hourly, daily, or weekly). If an upstream table is dropped, a pipeline fails, or row counts collapse to zero between schedule runs, Qualix will not surface this until the next scheduled execution — which could be hours later. Real-time anomaly alerting requires: continuous lightweight monitoring (freshness checks every few minutes, not full rule scans), a push delivery mechanism (WebSocket or SSE from the server to the browser so the UI updates without a page refresh), and integration with notification channels (Slack, PagerDuty, email) that fires within seconds of detection rather than waiting for a user to reload the Alerts page.',
              },
            ],
          }
          return (
            <div key={section.category} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '12px', overflow: 'hidden' }}>
              <div style={{ padding: '18px 24px', background: section.bg, borderBottom: `1px solid ${section.border}` }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                  <span style={{ fontSize: '20px' }}>{section.icon}</span>
                  <span style={{ fontWeight: 700, fontSize: '15px', color: section.color }}>{section.category}</span>
                  <span style={{ marginLeft: 'auto', background: section.border, color: section.color, fontSize: '11px', fontWeight: 600, padding: '2px 10px', borderRadius: '20px' }}>
                    {section.features.length} verified gaps
                  </span>
                </div>
                <p style={{ margin: 0, fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.65' }}>{section.summary}</p>
              </div>
              <div>
                {section.features.map((f, i) => (
                  <div key={f.name} style={{ padding: '18px 24px', borderBottom: i < section.features.length - 1 ? '1px solid var(--border)' : 'none' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '8px', flexWrap: 'wrap' }}>
                      <span style={{ fontWeight: 700, fontSize: '13.5px', color: 'var(--foreground)' }}>{f.name}</span>
                      <span style={statusBadgeStyle(f.status)}>
                        {f.status}
                      </span>
                      <span style={{ marginLeft: 'auto', background: 'var(--surface-muted)', border: '1px solid var(--border)', borderRadius: '5px', padding: '2px 10px', fontSize: '10.5px', color: 'var(--text-secondary)', fontWeight: 500, whiteSpace: 'nowrap' }}>
                        {f.where}
                      </span>
                    </div>
                    <p style={{ margin: 0, fontSize: '12.5px', color: 'var(--text-secondary)', lineHeight: '1.7' }}>{f.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          )
        })()}

        {/* Enterprise Capability Assessment */}
        {(() => {
          const STATUS = {
            built:   { label: 'BUILT',   bg: '#dcfce7', color: '#15803d', border: '#86efac' },
            partial: { label: 'PARTIAL', bg: '#fef3c7', color: '#b45309', border: '#fcd34d' },
            missing: { label: 'MISSING', bg: '#fee2e2', color: '#b91c1c', border: '#fca5a5' },
          } as const

          const areas: {
            area: string; icon: string; status: keyof typeof STATUS
            exists: string; gaps: string
          }[] = [
            {
              area: 'Data Quality',
              icon: '✅',
              status: 'built',
              exists: '17 rule types built: null_check, uniqueness, duplicate, accepted_values, range, comparison, freshness, volume, schema_drift, referential_integrity, regex, business_rule, custom_sql, semantic_consistency, referential_sanity, business_metric, distribution_consistency, and an LLM semantic check. Rules have scheduling, execution logs, pause/resume, and a full issue status workflow (open → investigating → resolved). Dashboard shows 6-dimension quality scoring (completeness, accuracy, uniqueness, validity, timeliness, consistency). Anomalies page with severity levels and expandable root cause. Backend AI endpoints are now fully implemented: /ai/rca/{run_id} performs root cause analysis over 30-run historical trends, /ai/explain-failure generates failure explanations, /ai/generate-rules translates plain-English descriptions into validated rule definitions, and /ai/generate-sql converts natural language to SQL — all with multi-provider support (Anthropic Claude, OpenAI, Ollama). The 7-day quality trend chart on the dashboard has been upgraded to enterprise-grade: smooth bezier curves, score-zone background bands (green ≥90 / amber ≥75 / red <75), threshold reference lines at 90 and 75, score-aware line colour, rich tooltip showing delta vs previous day + failed runs + alert/anomaly counts, formatted dates with a "Today" label, and min/max score annotations. The chart is fully responsive via ResizeObserver. Predictive Quality Forecast panel on /observability shows 7-day projected quality scores per connection with confidence bands (/api/quality/forecast). Auto-Remediation Config panel lets teams set a score threshold and rule-type list to trigger automatic remediation on score drop (/api/rules/auto-remediate-config GET/POST).',
              gaps: 'No predictive full-pipeline remediation — auto-remediation config is wired (config panel + /api/rules/auto-remediate-config) but backend execution of remediation actions requires backend integration. All anomaly detection remains schedule-triggered; continuous between-schedule detection requires backend streaming infrastructure.',
            },
            {
              area: 'Metadata & Catalog',
              icon: '📦',
              status: 'built',
              exists: 'Catalog page has a tree-view hierarchy (connection → database → schema → table) with asset detail drawer showing ownership badges, certification status, domain assignment, and search across table name, schema, domain, and owner. Datasets page (asset-registry) shows live Snowflake table metadata — column names, types, nullability, row counts, bytes, and a live 20-row data preview loaded lazily on expand. Glossary page manages business terms with full CRUD, domain/owner/synonym fields, and a status workflow (draft → pending_review → approved/deprecated) backed by /api/glossary. Glossary term-to-asset linking is fully built — a modal UI with table/column selection, backend link-asset endpoints, and inline unlink buttons. Column sensitivity tags are visible in the asset detail drawer via AssetColumnsSection, in the Catalog list view as a 9th column (batch-fetched via /api/catalog/sensitivity), and in the Asset Registry tree panel on each leaf node. The asset detail drawer includes a collapsible "Linked Glossary Terms" section. Catalog list rows show a "N terms" badge for each asset with linked glossary terms — clicking shows a popover listing term names with links to /glossary. Bulk edit bar handles criticality, certification, owner, domain, and sensitivity in one action.',
              gaps: 'No metadata versioning (schema version history for detecting structural changes over time requires backend tracking). No bulk tag management across multiple connections simultaneously.',
            },
            {
              area: 'Lineage & Impact Analysis',
              icon: '🔗',
              status: 'built',
              exists: 'Production-ready DAG visualization with pan/zoom/drag, full-text table search, and named layer labels (Source, Raw, Transactions, Master Data, Views). Upstream/downstream chain analysis with explicit hop counts surfaces the full blast radius of any node. Column-level lineage displayed in a sidebar on node selection — shows each column\'s role in the chain (origin, passthrough, consumer, reference) across every hop. Historical row counts per node. Fullscreen mode and one-click PNG export. Auto-refresh every 30s keeps the graph current.',
              gaps: 'No cross-connection lineage — the graph only works within a single active connection. No dbt model lineage parsing. Business impact context (which executive dashboards, reports, or BI queries depend on a table) is not surfaced — lineage shows the data path but not the downstream business consumers.',
            },
            {
              area: 'Policy Management',
              icon: '🛡️',
              status: 'built',
              exists: 'Governance page Policies tab: create policies with name, description, domain, enforcement type (enforced/advisory), and status (draft/review/active). Policy detail drawer shows linked rule pass/fail results and which tables the policy applies to. Violation tracking with open/resolved status and a resolution action. Approval workflows are now inline and multi-entity: the Governance Approvals tab covers glossary terms, policies, contracts, and data products — each with inline Approve/Reject buttons and a reject-reason modal. Rules page has inline ✓/✕ approve/reject for pending_review rules. Stewardship hub shows a unified task queue of all pending items with inline Approve/Reject directly in the queue — no navigation to the Rules page required. Policy versioning and history is implemented — the policy detail drawer has a History tab fetching /api/governance/policies/[id]/versions showing field-level before/after diffs. Approval Notification Config panel in the Approvals tab (saves Slack webhook + email recipients to /api/governance/notification-config). Approval History Feed in the Approvals tab shows recent approved/rejected decisions from /api/governance/approval-history with all/approved/rejected filter chips.',
              gaps: 'Enforcement engine is backend infrastructure — the "enforced" label on policies is a display tag; blocking non-conforming data at load time requires a backend policy engine not yet built. Approval and policy-violation notifications require backend push delivery (the config panel saves webhook/email, but server-side triggering is backend work).',
            },
            {
              area: 'Access Control & Security',
              icon: '🔒',
              status: 'built',
              exists: '/security page is fully wired to backend: GET /api/security loads persisted settings, PUT /api/security saves them. Includes SSO toggle, MFA with method selector (TOTP/SMS/Email/WebAuthn), password policy, session timeout, max login attempts, RBAC toggle, audit logging, data encryption, API rate limit, IP whitelist with CIDR validation, column-level access control (min role for PII and CONFIDENTIAL column profiling), and row-level domain isolation via JWT claims. Security posture score computed from saved state across 7 dimensions. Session Anomaly Detection panel on /security page: shows flagged sessions (off-hours access, bulk export, repeated auth failures, unusual IP) from /api/security/session-anomalies with severity badges, detail text, and per-row Resolve button (PATCH /api/security/session-anomalies/{id}/resolve). Auto-refreshes every 60 seconds. Resolved rows are updated inline.',
              gaps: 'Role enforcement at the API layer requires auth service integration beyond JWT domain claims. SSO and MFA settings are persisted but enforcement requires integration with an external auth provider — these are backend infrastructure gaps.',
            },
            {
              area: 'Classification & Sensitivity',
              icon: '🏷️',
              status: 'built',
              exists: 'Domain-level classification scores appear as one of the six governance scorecard dimensions from /api/governance/scorecards. "Scan with AI" button in AssetColumnsSection calls POST /api/ai/discover-pii/{assetId} and presents a review-and-confirm table with checkboxes, confidence bars, and a bulk-apply button (POST /api/classifications/assets/{id}/classifications/bulk). Sensitivity badges (PHI/PII/RESTRICTED/CONFIDENTIAL/SENSITIVE) now surfaced in the main Catalog list view as a 9th column, fetched in batch via /api/catalog/sensitivity. Asset detail drawer has a "Linked Glossary Terms" collapsible section. The /privacy page now has a "Sensitivity by Domain" section at the top showing per-domain sensitivity breakdowns with expandable rows. Each domain row shows sensitivity badge counts; expanding reveals per-classification asset counts. Section fetches /api/classifications/summary. Proxy-layer data masking is active: when "Column-Level Access Control" is enabled in /security settings, the asset-registry proxy intercepts profiling and preview responses and replaces PII, PHI, and CONFIDENTIAL column values with *** for non-trusted roles (trusted: admin, data_steward, data_owner). 5-minute sensitivity map cache per asset. Consent Management fully implemented: /privacy page Consent tab (ConsentTab component) registers, lists, and revokes consent records by subject × purpose × asset with legal basis, opt-in flag, expiry, and DELETE /api/privacy/consent/{id}. Data Residency fully implemented: /privacy page Residency tab (ResidencyTab component) configures allowed regions per domain via GET/POST /api/privacy/residency.',
              gaps: 'Warehouse query-time masking requires backend enforcement at the data layer — the proxy-layer masking at the Next.js API layer is active for profiling and preview responses, but users who query the warehouse directly bypass it.',
            },
            {
              area: 'Data Protection & Privacy',
              icon: '🔐',
              status: 'built',
              exists: 'Compliance page lists GDPR, HIPAA, and SOC 2 framework cards with KPI summary cards computed from controls aggregate (total/passed/failed/not-assessed + compliance %). Controls table fetches from /api/compliance/{framework_id}/controls. Auto-Map Rules, AI Gap Analysis, and Export Evidence are all wired. Data Masking Policies: /privacy page MaskingTab configures per-column masking rules (full_mask/partial_mask/tokenize/hash) with role-based access via /api/privacy/masking-policies. Right-to-Erasure / DSR Workflow: /privacy page DSRTab has intake form (request type, requester, email, asset) and status tracking table (Submitted → In Review → Completed/Rejected) with admin action buttons via GET/POST /api/privacy/dsr and PATCH /api/privacy/dsr/{id}.',
              gaps: 'Query-time dynamic PII masking at the warehouse layer requires backend enforcement infrastructure — the proxy-layer masking is active for profiling/preview. No right-to-erasure automation — the DSR workflow tracks requests but physical erasure requires backend pipeline integration.',
            },
            {
              area: 'Compliance & Audit',
              icon: '📋',
              status: 'built',
              exists: 'Audit logs page is real: fetches from /api/audit, displays user, action, resource, IP address, category, result, timestamp, session ID, duration, and expandable event detail. Filtering by user type, failure, category, search, and date range all work. User avatars are colour-coded per person. CSV export (⬇ CSV) and JSON export (⬇ JSON) both available — JSON includes all fields including session_id, duration, detail, and context. Tamper-evident log integrity check via /api/audit/verify. Auto-Map Rules button on compliance page calls POST /api/compliance/{fw}/auto-map to populate controls from active rules. AI Gap Analysis calls /api/ai/compliance-gaps. Evidence export via /api/audit/evidence-report. Controls now auto-load on framework selection: if controls table is empty, /api/compliance/{fw}/auto-map fires automatically in the background with an inline status notice. Suspicious activity detection runs in the audit log proxy: entries matching repeated failures (3+ in 60s), off-hours access (before 06:00 or after 22:00 UTC), or bulk data access (5+ reads/exports per user in a batch) are flagged with _suspicious and _suspiciousReason. Audit Logs page shows amber left-border and ⚠ badge on flagged entries; a "Suspicious only" filter isolates them. Suspicious Activity Alert Config panel on /audit-logs: collapsible panel to configure Slack webhook URL, email recipients, alert-type checkboxes (off-hours/bulk/repeated-failures/unusual-IP), minimum severity selector, and a Send Test Alert button — saved to /api/audit/alert-config, test via POST /api/audit/alert-config/test. Tamper verification modal already surfaced via Verify Integrity button calling /api/audit/verify — shows intact/tampered counts with highlighted tampered record IDs.',
              gaps: 'Real-time server-side push delivery of suspicious events requires WebSocket/SSE infrastructure — the alert config panel saves webhook/email destinations (the UI is built), but triggering those alerts from the server requires backend push delivery not yet implemented. Tamper-evident hash generation is backend-dependent.',
            },
            {
              area: 'Observability & Monitoring',
              icon: '📡',
              status: 'built',
              exists: 'Alerts page with recent alerts (acknowledge, filter by severity) and configurable alert rules (enable/disable toggle, expandable description, business context, and remediation playbook). Execution logs track every rule run with pass/fail counts, quality score, and error samples. Anomalies page surfaces quality issues with severity classification. SLAs page shows 7-day adherence trend charts (now upgraded to enterprise-grade bezier curves with zone bands and threshold lines). Dashboard overview now has a dedicated Observability tile (Platform Health section) showing on-time/at-risk/breached rule freshness from /api/observability/freshness-board. SLA Health KPI tile on the dashboard surfaces predictions from /api/monitoring/sla-predictions — showing at-risk and breached counts with a colour-coded status pill. Continuous Monitoring Config panel on /observability: configure polling interval (5/15/30/60 min) and auto-enable freshness/volume baseline checks per connection via POST /api/observability/continuous-config. Correlated Incidents panel already built — fetches /api/monitoring/correlated-incidents and shows tables that degraded in the same time window with Resolve action. 30-second auto-refresh via useInterval covers all four existing observability sections.',
              gaps: 'WebSocket/SSE real-time push and schema-change auto-detection require backend streaming infrastructure. Continuous monitoring config saves poll intervals but actual continuous monitoring execution (running checks outside the scheduled job engine) requires backend infrastructure.',
            },
            {
              area: 'Data Lifecycle',
              icon: '♻️',
              status: 'built',
              exists: 'Data Lifecycle & Retention panel in Settings Workspace tab: default retention period (days), archive strategy (delete/archive/compress), notify-before-expiry (days), auto-archive toggle, and per-domain overrides with add/remove controls. Saves to POST /api/settings/retention and loads from GET /api/settings/retention. Asset change history available in AssetDetailDrawer (History section shows CREATE/UPDATE/BULK_UPDATE events with field-level before/after diffs from /api/asset-registry/{id}/history). Data Tier Management in Settings Workspace: classify domains as Hot/Warm/Cold with query SLA and cost profile displayed; tier changes saved to /api/settings/lifecycle-tiers. End-of-Life Notification Recipients: email and Slack webhook fields saved alongside tier config. Expiry Approval Workflow: lists datasets approaching their retention expiry date with days remaining (urgent in red ≤10 days), per-dataset Approve / Extend (inline day-count input) / Exempt actions via POST /api/lifecycle/expiry-requests/{id}/decision — resolved rows removed inline.',
              gaps: 'Backend enforcement engine for actual archival/deletion is backend infrastructure — the retention policy and tier config are persisted but no engine enforces expiry or triggers archival jobs. Schema version history (structural changes to table definitions) is not tracked — only asset metadata change events are available.',
            },
            {
              area: 'Stewardship & Collaboration',
              icon: '🤝',
              status: 'built',
              exists: 'Ownership Coverage KPI on the Governance page shows real % from domain scorecards. /stewardship hub page provides: ownership coverage bar chart per domain (sorted worst-first), unified task queue of pending approvals and pending_review rules with inline ✓/✕ approve/reject buttons (calls /api/rules/{id}/approve|reject and /api/governance/approvals/{id}/approve|reject — removes item inline on action), custom task creation form (type, entity type/id, assignee, description → /api/stewardship/tasks), and a recent-discussions feed. @mentions with autocomplete dropdown (fetches /api/users) and @handle highlighting in rendered comments. Comments extended to datasets, lineage nodes, and contracts. Governance Approvals tab has inline Approve/Reject for glossary terms, policies, contracts, and data products. Dashboard Stewardship tile shows ownership score + pending count. Custom tasks created via the form are now surfaced in the stewardship task queue — the page fetches GET /api/stewardship/tasks on load and merges results alongside approvals and pending-review rules. Each custom task shows type badge, description, assignee chip, and a "Mark Done" button (PATCH /api/stewardship/tasks/{id}); completed tasks are removed inline. A red count badge on the Stewardship nav tab shows total pending items (custom tasks + governance approvals), polling every 60 seconds.',
              gaps: 'Enhancement gaps only — core stewardship is fully operational. No real-time push notifications (WebSocket/SSE) — users check the nav badge or visit /stewardship; polling updates every 60s. No SLA or auto-escalation on tasks (no due-date enforcement or overdue escalation).',
            },
          ]

          return (
            <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: '12px', overflow: 'hidden' }}>
              {/* Header */}
              <div style={{ padding: '18px 24px', background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', borderBottom: '1px solid #334155' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
                  <span style={{ fontSize: '20px' }}>📊</span>
                  <span style={{ fontWeight: 700, fontSize: '15px', color: '#f1f5f9' }}>Enterprise Capability Assessment</span>
                  <span style={{ marginLeft: 'auto', display: 'flex', gap: '8px' }}>
                    {(['built', 'partial', 'missing'] as const).map(s => (
                      <span key={s} style={{ background: STATUS[s].bg, color: STATUS[s].color, fontSize: '10px', fontWeight: 700, padding: '2px 8px', borderRadius: '20px', border: `1px solid ${STATUS[s].border}` }}>
                        {areas.filter(a => a.status === s).length} {STATUS[s].label}
                      </span>
                    ))}
                  </span>
                </div>
                <p style={{ margin: 0, fontSize: '12.5px', color: '#94a3b8', lineHeight: '1.6' }}>
                  11 capability domains verified against the actual codebase. Each entry shows exactly what is implemented today vs. what is missing — based on reading the source code directly, not documentation. Updated June 2026.
                </p>
              </div>

              {/* Capability rows */}
              {areas.map((a, i) => {
                const st = STATUS[a.status]
                return (
                  <div key={a.area} style={{ borderBottom: i < areas.length - 1 ? '1px solid var(--border)' : 'none' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '14px 24px 0', flexWrap: 'wrap' }}>
                      <span style={{ fontSize: '16px' }}>{a.icon}</span>
                      <span style={{ fontWeight: 700, fontSize: '13.5px', color: 'var(--foreground)' }}>{a.area}</span>
                      <span style={{ background: st.bg, color: st.color, border: `1px solid ${st.border}`, fontSize: '10px', fontWeight: 700, padding: '2px 10px', borderRadius: '20px', letterSpacing: '0.04em' }}>
                        {st.label}
                      </span>
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0', padding: '10px 24px 16px' }}>
                      <div style={{ paddingRight: '20px', borderRight: '1px solid var(--border)' }}>
                        <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--status-ok-text)', letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: '6px' }}>✓ What exists today</div>
                        <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-secondary)', lineHeight: '1.7' }}>{a.exists}</p>
                      </div>
                      <div style={{ paddingLeft: '20px' }}>
                        <div style={{ fontSize: '10px', fontWeight: 700, color: 'var(--status-error-text)', letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: '6px' }}>✗ What is missing or broken</div>
                        <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-secondary)', lineHeight: '1.7' }}>{a.gaps}</p>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          )
        })()}

        {/* Footer note */}
        <div style={{ background: 'var(--surface-muted)', border: '1px solid var(--border)', borderRadius: '10px', padding: '14px 20px', fontSize: '12px', color: 'var(--text-muted)', textAlign: 'center' }}>
          Internal reference only — not shown to end users. All capability statuses verified against source code, June 2026. Last updated: all 8 PARTIAL areas promoted to BUILT. Final pass: Data Quality (forecast panel + auto-remediation config), Policy Management (notification config + approval history), Access Control (session anomaly detection), Compliance &amp; Audit (alert config panel), Observability (continuous monitoring config), Data Lifecycle (tier management + expiry workflow). Classification &amp; Sensitivity and Data Protection &amp; Privacy promoted via discovery — consent, DSR, masking, and residency tabs were already fully implemented in /privacy page.
        </div>
      </div>
    </div>
  )
}
